apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nri-db.fullname" . }}-config
  labels:
    {{- include "nri-db.labels" . | nindent 4 }}
data:
  plugin.json: |
    {
      "global": {
        "account_id": "{{ .Values.pluginConfig.accountId }}",
        "insights_mode": {
          "insights_insert_key": "{{ .Values.pluginConfig.insertKey }}"
        }
      },
      "agents": {{- toJson .Values.pluginConfig.agents }}
    }
  logging.properties: |    
    ############################################################
    #   Global properties
    ############################################################
    
    handlers = java.util.logging.ConsoleHandler
    
    # Default global logging level.
    .level = INFO
    
    ############################################################
    # Handler specific properties.
    ############################################################
    
    # Console formatter
    java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
    
    # Example to customize the SimpleFormatter output format
    java.util.logging.SimpleFormatter.format = [%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] %4$-10s %2$s - %5$s%6$s%n
    
    ############################################################
    # Facility specific properties.
    ############################################################
    
    #com.xyz.foo.level = SEVERE
