apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nri-db.fullname" . }}
  labels:
    {{- include "nri-db.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nri-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nri-db.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nri-db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: NRIDB_ENCRYPTION_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "nri-db.fullname" . }}-secret
                key: encryptionPassword
          volumeMounts:
          - mountPath: /app/nri-db/config
            name: config-volume
          - mountPath: /app/nri-db/inputs
            name: inputs-volume
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "nri-db.fullname" . }}-config
      - name: inputs-volume
        configMap:
          name: {{ include "nri-db.fullname" . }}-inputs-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
